{% set name = "opentelemetry-instrumentation-threading" %}
{% set version = "0.60b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_threading-{{ version }}.tar.gz
  sha256: 9af6d53aa28d4364700b15e31a70e0dbb7801b1d0eb596153dd3b50ab291650a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation =={{ version }}
    - wrapt >=1.0.0,<2.0.0

test:
  imports:
    - opentelemetry.instrumentation.threading
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://opentelemetry.io
  dev_url: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-threading
  doc_url: https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/threading/threading.html
  summary: Thread context propagation support for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
