{% set name = "opentelemetry-instrumentation-threading" %}
{% set version = "0.54b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_threading-{{ version }}.tar.gz
  sha256: 74677085514d0f3a0f77593fc515812f6048ec47023e618ee02c6d80ad02306a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation =={{ version }}
    - wrapt >=1.0.0,<2.0.0

test:
  imports:
    - opentelemetry.instrumentation.threading
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: Thread context propagation support for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
